// SOH [Chinese] - OTR declarations for Simplified Chinese UI textures.
//
// Auto-generated by scripts/chinese/generate_assets.py in upstream
// Shipwright-CN, then hand-maintained here. Kept in a standalone header
// (rather than appended to the generated textures/*/*.h files) so that
// regenerating asset headers cannot wipe the Chinese additions.
//
// The matching .png sources live in soh/assets/custom/textures/<folder>/
// and are packed into soh.otr by the ExtractAssets target.

#ifndef TEXTURES_CHINESE_TEXTURES_H
#define TEXTURES_CHINESE_TEXTURES_H 1

#include "align_asset_macro.h"

// #region SOH [Chinese]

// --- do_action_static ---
#define dgAttackDoActionCHITex "__OTR__textures/do_action_static/gAttackDoActionCHITex"
static const ALIGN_ASSET(2) char gAttackDoActionCHITex[] = dgAttackDoActionCHITex;
#define dgCheckDoActionCHITex "__OTR__textures/do_action_static/gCheckDoActionCHITex"
static const ALIGN_ASSET(2) char gCheckDoActionCHITex[] = dgCheckDoActionCHITex;
#define dgClimbDoActionCHITex "__OTR__textures/do_action_static/gClimbDoActionCHITex"
static const ALIGN_ASSET(2) char gClimbDoActionCHITex[] = dgClimbDoActionCHITex;
#define dgDecideDoActionCHITex "__OTR__textures/do_action_static/gDecideDoActionCHITex"
static const ALIGN_ASSET(2) char gDecideDoActionCHITex[] = dgDecideDoActionCHITex;
#define dgDiveDoActionCHITex "__OTR__textures/do_action_static/gDiveDoActionCHITex"
static const ALIGN_ASSET(2) char gDiveDoActionCHITex[] = dgDiveDoActionCHITex;
#define dgDownDoActionCHITex "__OTR__textures/do_action_static/gDownDoActionCHITex"
static const ALIGN_ASSET(2) char gDownDoActionCHITex[] = dgDownDoActionCHITex;
#define dgDropDoActionCHITex "__OTR__textures/do_action_static/gDropDoActionCHITex"
static const ALIGN_ASSET(2) char gDropDoActionCHITex[] = dgDropDoActionCHITex;
#define dgEnterDoActionCHITex "__OTR__textures/do_action_static/gEnterDoActionCHITex"
static const ALIGN_ASSET(2) char gEnterDoActionCHITex[] = dgEnterDoActionCHITex;
#define dgFasterDoActionCHITex "__OTR__textures/do_action_static/gFasterDoActionCHITex"
static const ALIGN_ASSET(2) char gFasterDoActionCHITex[] = dgFasterDoActionCHITex;
#define dgGrabDoActionCHITex "__OTR__textures/do_action_static/gGrabDoActionCHITex"
static const ALIGN_ASSET(2) char gGrabDoActionCHITex[] = dgGrabDoActionCHITex;
#define dgJumpDoActionCHITex "__OTR__textures/do_action_static/gJumpDoActionCHITex"
static const ALIGN_ASSET(2) char gJumpDoActionCHITex[] = dgJumpDoActionCHITex;
#define dgNextDoActionCHITex "__OTR__textures/do_action_static/gNextDoActionCHITex"
static const ALIGN_ASSET(2) char gNextDoActionCHITex[] = dgNextDoActionCHITex;
#define dgNum1DoActionCHITex "__OTR__textures/do_action_static/gNum1DoActionCHITex"
static const ALIGN_ASSET(2) char gNum1DoActionCHITex[] = dgNum1DoActionCHITex;
#define dgNum2DoActionCHITex "__OTR__textures/do_action_static/gNum2DoActionCHITex"
static const ALIGN_ASSET(2) char gNum2DoActionCHITex[] = dgNum2DoActionCHITex;
#define dgNum3DoActionCHITex "__OTR__textures/do_action_static/gNum3DoActionCHITex"
static const ALIGN_ASSET(2) char gNum3DoActionCHITex[] = dgNum3DoActionCHITex;
#define dgNum4DoActionCHITex "__OTR__textures/do_action_static/gNum4DoActionCHITex"
static const ALIGN_ASSET(2) char gNum4DoActionCHITex[] = dgNum4DoActionCHITex;
#define dgNum5DoActionCHITex "__OTR__textures/do_action_static/gNum5DoActionCHITex"
static const ALIGN_ASSET(2) char gNum5DoActionCHITex[] = dgNum5DoActionCHITex;
#define dgNum6DoActionCHITex "__OTR__textures/do_action_static/gNum6DoActionCHITex"
static const ALIGN_ASSET(2) char gNum6DoActionCHITex[] = dgNum6DoActionCHITex;
#define dgNum7DoActionCHITex "__OTR__textures/do_action_static/gNum7DoActionCHITex"
static const ALIGN_ASSET(2) char gNum7DoActionCHITex[] = dgNum7DoActionCHITex;
#define dgNum8DoActionCHITex "__OTR__textures/do_action_static/gNum8DoActionCHITex"
static const ALIGN_ASSET(2) char gNum8DoActionCHITex[] = dgNum8DoActionCHITex;
#define dgOpenDoActionCHITex "__OTR__textures/do_action_static/gOpenDoActionCHITex"
static const ALIGN_ASSET(2) char gOpenDoActionCHITex[] = dgOpenDoActionCHITex;
#define dgPutAwayDoActionCHITex "__OTR__textures/do_action_static/gPutAwayDoActionCHITex"
static const ALIGN_ASSET(2) char gPutAwayDoActionCHITex[] = dgPutAwayDoActionCHITex;
#define dgReelDoActionCHITex "__OTR__textures/do_action_static/gReelDoActionCHITex"
static const ALIGN_ASSET(2) char gReelDoActionCHITex[] = dgReelDoActionCHITex;
#define dgReturnDoActionCHITex "__OTR__textures/do_action_static/gReturnDoActionCHITex"
static const ALIGN_ASSET(2) char gReturnDoActionCHITex[] = dgReturnDoActionCHITex;
#define dgSaveDoActionCHITex "__OTR__textures/do_action_static/gSaveDoActionCHITex"
static const ALIGN_ASSET(2) char gSaveDoActionCHITex[] = dgSaveDoActionCHITex;
#define dgSpeakDoActionCHITex "__OTR__textures/do_action_static/gSpeakDoActionCHITex"
static const ALIGN_ASSET(2) char gSpeakDoActionCHITex[] = dgSpeakDoActionCHITex;
#define dgStopDoActionCHITex "__OTR__textures/do_action_static/gStopDoActionCHITex"
static const ALIGN_ASSET(2) char gStopDoActionCHITex[] = dgStopDoActionCHITex;
#define dgThrowDoActionCHITex "__OTR__textures/do_action_static/gThrowDoActionCHITex"
static const ALIGN_ASSET(2) char gThrowDoActionCHITex[] = dgThrowDoActionCHITex;
#define dgUnusedNaviDoActionCHITex "__OTR__textures/do_action_static/gUnusedNaviDoActionCHITex"
static const ALIGN_ASSET(2) char gUnusedNaviDoActionCHITex[] = dgUnusedNaviDoActionCHITex;

// --- g_pn_01 ---
#define dgForestTempleTitleCardCHITex "__OTR__textures/g_pn_01/gForestTempleTitleCardCHITex"
static const ALIGN_ASSET(2) char gForestTempleTitleCardCHITex[] = dgForestTempleTitleCardCHITex;

// --- g_pn_02 ---
#define dgShadowTempleTitleCardCHITex "__OTR__textures/g_pn_02/gShadowTempleTitleCardCHITex"
static const ALIGN_ASSET(2) char gShadowTempleTitleCardCHITex[] = dgShadowTempleTitleCardCHITex;

// --- g_pn_03 ---
#define dgFireTempleTitleCardCHITex "__OTR__textures/g_pn_03/gFireTempleTitleCardCHITex"
static const ALIGN_ASSET(2) char gFireTempleTitleCardCHITex[] = dgFireTempleTitleCardCHITex;

// --- g_pn_04 ---
#define dgWaterTempleTitleCardCHITex "__OTR__textures/g_pn_04/gWaterTempleTitleCardCHITex"
static const ALIGN_ASSET(2) char gWaterTempleTitleCardCHITex[] = dgWaterTempleTitleCardCHITex;

// --- g_pn_05 ---
#define dgSpiritTempleTitleCardCHITex "__OTR__textures/g_pn_05/gSpiritTempleTitleCardCHITex"
static const ALIGN_ASSET(2) char gSpiritTempleTitleCardCHITex[] = dgSpiritTempleTitleCardCHITex;

// --- g_pn_06 ---
#define dgDekuTreeTitleCardCHITex "__OTR__textures/g_pn_06/gDekuTreeTitleCardCHITex"
static const ALIGN_ASSET(2) char gDekuTreeTitleCardCHITex[] = dgDekuTreeTitleCardCHITex;

// --- g_pn_07 ---
#define dgJabuJabuTitleCardCHITex "__OTR__textures/g_pn_07/gJabuJabuTitleCardCHITex"
static const ALIGN_ASSET(2) char gJabuJabuTitleCardCHITex[] = dgJabuJabuTitleCardCHITex;

// --- g_pn_08 ---
#define dgDodongosCavernTitleCardCHITex "__OTR__textures/g_pn_08/gDodongosCavernTitleCardCHITex"
static const ALIGN_ASSET(2) char gDodongosCavernTitleCardCHITex[] = dgDodongosCavernTitleCardCHITex;

// --- g_pn_09 ---
#define dgInsideGanonsCastleTitleCardCHITex "__OTR__textures/g_pn_09/gInsideGanonsCastleTitleCardCHITex"
static const ALIGN_ASSET(2) char gInsideGanonsCastleTitleCardCHITex[] = dgInsideGanonsCastleTitleCardCHITex;

// --- g_pn_10 ---
#define dgIceCavernTitleCardCHITex "__OTR__textures/g_pn_10/gIceCavernTitleCardCHITex"
static const ALIGN_ASSET(2) char gIceCavernTitleCardCHITex[] = dgIceCavernTitleCardCHITex;

// --- g_pn_11 ---
#define dgGERudoTrainingGroundTitleCardCHITex "__OTR__textures/g_pn_11/gGERudoTrainingGroundTitleCardCHITex"
static const ALIGN_ASSET(2) char gGERudoTrainingGroundTitleCardCHITex[] = dgGERudoTrainingGroundTitleCardCHITex;

// --- g_pn_12 ---
#define dgCastleCourtyardTitleCardCHITex "__OTR__textures/g_pn_12/gCastleCourtyardTitleCardCHITex"
static const ALIGN_ASSET(2) char gCastleCourtyardTitleCardCHITex[] = dgCastleCourtyardTitleCardCHITex;

// --- g_pn_13 ---
#define dgGreatFairysFountainTitleCardCHITex "__OTR__textures/g_pn_13/gGreatFairysFountainTitleCardCHITex"
static const ALIGN_ASSET(2) char gGreatFairysFountainTitleCardCHITex[] = dgGreatFairysFountainTitleCardCHITex;

// --- g_pn_14 ---
#define dgChamberOfTheSagesTitleCardCHITex "__OTR__textures/g_pn_14/gChamberOfTheSagesTitleCardCHITex"
static const ALIGN_ASSET(2) char gChamberOfTheSagesTitleCardCHITex[] = dgChamberOfTheSagesTitleCardCHITex;

// --- g_pn_15 ---
#define dgShootingGalleryTitleCardCHITex "__OTR__textures/g_pn_15/gShootingGalleryTitleCardCHITex"
static const ALIGN_ASSET(2) char gShootingGalleryTitleCardCHITex[] = dgShootingGalleryTitleCardCHITex;

// --- g_pn_16 ---
#define dgTempleOfTimeTitleCardCHITex "__OTR__textures/g_pn_16/gTempleOfTimeTitleCardCHITex"
static const ALIGN_ASSET(2) char gTempleOfTimeTitleCardCHITex[] = dgTempleOfTimeTitleCardCHITex;

// --- g_pn_17 ---
#define dgMarketTitleCardCHITex "__OTR__textures/g_pn_17/gMarketTitleCardCHITex"
static const ALIGN_ASSET(2) char gMarketTitleCardCHITex[] = dgMarketTitleCardCHITex;

// --- g_pn_18 ---
#define dgBackAlleyTitleCardCHITex "__OTR__textures/g_pn_18/gBackAlleyTitleCardCHITex"
static const ALIGN_ASSET(2) char gBackAlleyTitleCardCHITex[] = dgBackAlleyTitleCardCHITex;

// --- g_pn_19 ---
#define dgKokiriShopTitleCardCHITex "__OTR__textures/g_pn_19/gKokiriShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gKokiriShopTitleCardCHITex[] = dgKokiriShopTitleCardCHITex;

// --- g_pn_20 ---
#define dgGoronShopTitleCardCHITex "__OTR__textures/g_pn_20/gGoronShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gGoronShopTitleCardCHITex[] = dgGoronShopTitleCardCHITex;

// --- g_pn_21 ---
#define dgZoraShopTitleCardCHITex "__OTR__textures/g_pn_21/gZoraShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gZoraShopTitleCardCHITex[] = dgZoraShopTitleCardCHITex;

// --- g_pn_22 ---
#define dgHouseOfSkulltulaTitleCardCHITex "__OTR__textures/g_pn_22/gHouseOfSkulltulaTitleCardCHITex"
static const ALIGN_ASSET(2) char gHouseOfSkulltulaTitleCardCHITex[] = dgHouseOfSkulltulaTitleCardCHITex;

// --- g_pn_23 ---
#define dgBazaarTitleCardCHITex "__OTR__textures/g_pn_23/gBazaarTitleCardCHITex"
static const ALIGN_ASSET(2) char gBazaarTitleCardCHITex[] = dgBazaarTitleCardCHITex;

// --- g_pn_24 ---
#define dgPotionShopTitleCardCHITex "__OTR__textures/g_pn_24/gPotionShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gPotionShopTitleCardCHITex[] = dgPotionShopTitleCardCHITex;

// --- g_pn_25 ---
#define dgGravekeepersHutTitleCardCHITex "__OTR__textures/g_pn_25/gGravekeepersHutTitleCardCHITex"
static const ALIGN_ASSET(2) char gGravekeepersHutTitleCardCHITex[] = dgGravekeepersHutTitleCardCHITex;

// --- g_pn_26 ---
#define dgLakesideLaboratoryTitleCardCHITex "__OTR__textures/g_pn_26/gLakesideLaboratoryTitleCardCHITex"
static const ALIGN_ASSET(2) char gLakesideLaboratoryTitleCardCHITex[] = dgLakesideLaboratoryTitleCardCHITex;

// --- g_pn_27 ---
#define dgHyruleFieldTitleCardCHITex "__OTR__textures/g_pn_27/gHyruleFieldTitleCardCHITex"
static const ALIGN_ASSET(2) char gHyruleFieldTitleCardCHITex[] = dgHyruleFieldTitleCardCHITex;

// --- g_pn_28 ---
#define dgKakarikoVillageTitleCardCHITex "__OTR__textures/g_pn_28/gKakarikoVillageTitleCardCHITex"
static const ALIGN_ASSET(2) char gKakarikoVillageTitleCardCHITex[] = dgKakarikoVillageTitleCardCHITex;

// --- g_pn_29 ---
#define dgGraveyardTitleCardCHITex "__OTR__textures/g_pn_29/gGraveyardTitleCardCHITex"
static const ALIGN_ASSET(2) char gGraveyardTitleCardCHITex[] = dgGraveyardTitleCardCHITex;

// --- g_pn_30 ---
#define dgZorasRiverTitleCardCHITex "__OTR__textures/g_pn_30/gZorasRiverTitleCardCHITex"
static const ALIGN_ASSET(2) char gZorasRiverTitleCardCHITex[] = dgZorasRiverTitleCardCHITex;

// --- g_pn_31 ---
#define dgKokiriForestTitleCardCHITex "__OTR__textures/g_pn_31/gKokiriForestTitleCardCHITex"
static const ALIGN_ASSET(2) char gKokiriForestTitleCardCHITex[] = dgKokiriForestTitleCardCHITex;

// --- g_pn_32 ---
#define dgLakeHyliaTitleCardCHITex "__OTR__textures/g_pn_32/gLakeHyliaTitleCardCHITex"
static const ALIGN_ASSET(2) char gLakeHyliaTitleCardCHITex[] = dgLakeHyliaTitleCardCHITex;

// --- g_pn_33 ---
#define dgZorasDomainTitleCardCHITex "__OTR__textures/g_pn_33/gZorasDomainTitleCardCHITex"
static const ALIGN_ASSET(2) char gZorasDomainTitleCardCHITex[] = dgZorasDomainTitleCardCHITex;

// --- g_pn_34 ---
#define dgZorasFountainTitleCardCHITex "__OTR__textures/g_pn_34/gZorasFountainTitleCardCHITex"
static const ALIGN_ASSET(2) char gZorasFountainTitleCardCHITex[] = dgZorasFountainTitleCardCHITex;

// --- g_pn_35 ---
#define dgGERudoValleyTitleCardCHITex "__OTR__textures/g_pn_35/gGERudoValleyTitleCardCHITex"
static const ALIGN_ASSET(2) char gGERudoValleyTitleCardCHITex[] = dgGERudoValleyTitleCardCHITex;

// --- g_pn_36 ---
#define dgLostWoodsTitleCardCHITex "__OTR__textures/g_pn_36/gLostWoodsTitleCardCHITex"
static const ALIGN_ASSET(2) char gLostWoodsTitleCardCHITex[] = dgLostWoodsTitleCardCHITex;

// --- g_pn_37 ---
#define dgHauntedWastelandTitleCardCHITex "__OTR__textures/g_pn_37/gHauntedWastelandTitleCardCHITex"
static const ALIGN_ASSET(2) char gHauntedWastelandTitleCardCHITex[] = dgHauntedWastelandTitleCardCHITex;

// --- g_pn_38 ---
#define dgHyruleCastleTitleCardCHITex "__OTR__textures/g_pn_38/gHyruleCastleTitleCardCHITex"
static const ALIGN_ASSET(2) char gHyruleCastleTitleCardCHITex[] = dgHyruleCastleTitleCardCHITex;

// --- g_pn_39 ---
#define dgDeathMountainTrailTitleCardCHITex "__OTR__textures/g_pn_39/gDeathMountainTrailTitleCardCHITex"
static const ALIGN_ASSET(2) char gDeathMountainTrailTitleCardCHITex[] = dgDeathMountainTrailTitleCardCHITex;

// --- g_pn_40 ---
#define dgDeathMountainCraterTitleCardCHITex "__OTR__textures/g_pn_40/gDeathMountainCraterTitleCardCHITex"
static const ALIGN_ASSET(2) char gDeathMountainCraterTitleCardCHITex[] = dgDeathMountainCraterTitleCardCHITex;

// --- g_pn_41 ---
#define dgGoronCityTitleCardCHITex "__OTR__textures/g_pn_41/gGoronCityTitleCardCHITex"
static const ALIGN_ASSET(2) char gGoronCityTitleCardCHITex[] = dgGoronCityTitleCardCHITex;

// --- g_pn_42 ---
#define dgLonLonRanchTitleCardCHITex "__OTR__textures/g_pn_42/gLonLonRanchTitleCardCHITex"
static const ALIGN_ASSET(2) char gLonLonRanchTitleCardCHITex[] = dgLonLonRanchTitleCardCHITex;

// --- g_pn_43 ---
#define dgGanonsCastleTitleCardCHITex "__OTR__textures/g_pn_43/gGanonsCastleTitleCardCHITex"
static const ALIGN_ASSET(2) char gGanonsCastleTitleCardCHITex[] = dgGanonsCastleTitleCardCHITex;

// --- g_pn_44 ---
#define dgRoyalFamilysTombTitleCardCHITex "__OTR__textures/g_pn_44/gRoyalFamilysTombTitleCardCHITex"
static const ALIGN_ASSET(2) char gRoyalFamilysTombTitleCardCHITex[] = dgRoyalFamilysTombTitleCardCHITex;

// --- g_pn_45 ---
#define dgFairysFountainTitleCardCHITex "__OTR__textures/g_pn_45/gFairysFountainTitleCardCHITex"
static const ALIGN_ASSET(2) char gFairysFountainTitleCardCHITex[] = dgFairysFountainTitleCardCHITex;

// --- g_pn_46 ---
#define dgFishingPondTitleCardCHITex "__OTR__textures/g_pn_46/gFishingPondTitleCardCHITex"
static const ALIGN_ASSET(2) char gFishingPondTitleCardCHITex[] = dgFishingPondTitleCardCHITex;

// --- g_pn_47 ---
#define dgBombchuBowlingAlleyCardCHITex "__OTR__textures/g_pn_47/gBombchuBowlingAlleyCardCHITex"
static const ALIGN_ASSET(2) char gBombchuBowlingAlleyCardCHITex[] = dgBombchuBowlingAlleyCardCHITex;

// --- g_pn_48 ---
#define dgStableTitleCardCHITex "__OTR__textures/g_pn_48/gStableTitleCardCHITex"
static const ALIGN_ASSET(2) char gStableTitleCardCHITex[] = dgStableTitleCardCHITex;

// --- g_pn_49 ---
#define dgThievesHideoutTitleCardCHITex "__OTR__textures/g_pn_49/gThievesHideoutTitleCardCHITex"
static const ALIGN_ASSET(2) char gThievesHideoutTitleCardCHITex[] = dgThievesHideoutTitleCardCHITex;

// --- g_pn_50 ---
#define dgHappyMaskShopTitleCardCHITex "__OTR__textures/g_pn_50/gHappyMaskShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gHappyMaskShopTitleCardCHITex[] = dgHappyMaskShopTitleCardCHITex;

// --- g_pn_51 ---
#define dgTreasureBoxShopTitleCardCHITex "__OTR__textures/g_pn_51/gTreasureBoxShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gTreasureBoxShopTitleCardCHITex[] = dgTreasureBoxShopTitleCardCHITex;

// --- g_pn_52 ---
#define dgSacredForestMeadowTitleCardCHITex "__OTR__textures/g_pn_52/gSacredForestMeadowTitleCardCHITex"
static const ALIGN_ASSET(2) char gSacredForestMeadowTitleCardCHITex[] = dgSacredForestMeadowTitleCardCHITex;

// --- g_pn_53 ---
#define dgGERudosFortressTitleCardCHITex "__OTR__textures/g_pn_53/gGERudosFortressTitleCardCHITex"
static const ALIGN_ASSET(2) char gGERudosFortressTitleCardCHITex[] = dgGERudosFortressTitleCardCHITex;

// --- g_pn_54 ---
#define dgBottomOfTheWellTitleCardCHITex "__OTR__textures/g_pn_54/gBottomOfTheWellTitleCardCHITex"
static const ALIGN_ASSET(2) char gBottomOfTheWellTitleCardCHITex[] = dgBottomOfTheWellTitleCardCHITex;

// --- g_pn_55 ---
#define dgDesertColossusTitleCardCHITex "__OTR__textures/g_pn_55/gDesertColossusTitleCardCHITex"
static const ALIGN_ASSET(2) char gDesertColossusTitleCardCHITex[] = dgDesertColossusTitleCardCHITex;

// --- g_pn_56 ---
#define dgBombchuShopTitleCardCHITex "__OTR__textures/g_pn_56/gBombchuShopTitleCardCHITex"
static const ALIGN_ASSET(2) char gBombchuShopTitleCardCHITex[] = dgBombchuShopTitleCardCHITex;

// --- g_pn_57 ---
#define dgQuestionMarkTitleCardCHITex "__OTR__textures/g_pn_57/gQuestionMarkTitleCardCHITex"
static const ALIGN_ASSET(2) char gQuestionMarkTitleCardCHITex[] = dgQuestionMarkTitleCardCHITex;

// --- icon_item_gameover_static ---
#define dgContinuePlayingCHITex "__OTR__textures/icon_item_gameover_static/gContinuePlayingCHITex"
static const ALIGN_ASSET(2) char gContinuePlayingCHITex[] = dgContinuePlayingCHITex;
#define dgGameOverP1CHITex "__OTR__textures/icon_item_gameover_static/gGameOverP1CHITex"
static const ALIGN_ASSET(2) char gGameOverP1CHITex[] = dgGameOverP1CHITex;
#define dgGameOverP2CHITex "__OTR__textures/icon_item_gameover_static/gGameOverP2CHITex"
static const ALIGN_ASSET(2) char gGameOverP2CHITex[] = dgGameOverP2CHITex;
#define dgGameOverP3CHITex "__OTR__textures/icon_item_gameover_static/gGameOverP3CHITex"
static const ALIGN_ASSET(2) char gGameOverP3CHITex[] = dgGameOverP3CHITex;

// --- icon_item_nes_static ---
#define dgPauseBotWTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseBotWTitleCHITex"
static const ALIGN_ASSET(2) char gPauseBotWTitleCHITex[] = dgPauseBotWTitleCHITex;
#define dgPauseCurrentPositionCHITex "__OTR__textures/icon_item_nes_static/gPauseCurrentPositionCHITex"
static const ALIGN_ASSET(2) char gPauseCurrentPositionCHITex[] = dgPauseCurrentPositionCHITex;
#define dgPauseDekuTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseDekuTitleCHITex"
static const ALIGN_ASSET(2) char gPauseDekuTitleCHITex[] = dgPauseDekuTitleCHITex;
#define dgPauseDodongoTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseDodongoTitleCHITex"
static const ALIGN_ASSET(2) char gPauseDodongoTitleCHITex[] = dgPauseDodongoTitleCHITex;
#define dgPauseEquipment10CHITex "__OTR__textures/icon_item_nes_static/gPauseEquipment10CHITex"
static const ALIGN_ASSET(2) char gPauseEquipment10CHITex[] = dgPauseEquipment10CHITex;
#define dgPauseFireTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseFireTitleCHITex"
static const ALIGN_ASSET(2) char gPauseFireTitleCHITex[] = dgPauseFireTitleCHITex;
#define dgPauseForestTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseForestTitleCHITex"
static const ALIGN_ASSET(2) char gPauseForestTitleCHITex[] = dgPauseForestTitleCHITex;
#define dgPauseIceCavernTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseIceCavernTitleCHITex"
static const ALIGN_ASSET(2) char gPauseIceCavernTitleCHITex[] = dgPauseIceCavernTitleCHITex;
#define dgPauseJabuTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseJabuTitleCHITex"
static const ALIGN_ASSET(2) char gPauseJabuTitleCHITex[] = dgPauseJabuTitleCHITex;
#define dgPauseMap10CHITex "__OTR__textures/icon_item_nes_static/gPauseMap10CHITex"
static const ALIGN_ASSET(2) char gPauseMap10CHITex[] = dgPauseMap10CHITex;
#define dgPauseNoCHITex "__OTR__textures/icon_item_nes_static/gPauseNoCHITex"
static const ALIGN_ASSET(2) char gPauseNoCHITex[] = dgPauseNoCHITex;
#define dgPauseQuestStatus00CHITex "__OTR__textures/icon_item_nes_static/gPauseQuestStatus00CHITex"
static const ALIGN_ASSET(2) char gPauseQuestStatus00CHITex[] = dgPauseQuestStatus00CHITex;
#define dgPauseQuestStatus10CHITex "__OTR__textures/icon_item_nes_static/gPauseQuestStatus10CHITex"
static const ALIGN_ASSET(2) char gPauseQuestStatus10CHITex[] = dgPauseQuestStatus10CHITex;
#define dgPauseQuestStatus20CHITex "__OTR__textures/icon_item_nes_static/gPauseQuestStatus20CHITex"
static const ALIGN_ASSET(2) char gPauseQuestStatus20CHITex[] = dgPauseQuestStatus20CHITex;
#define dgPauseSave10CHITex "__OTR__textures/icon_item_nes_static/gPauseSave10CHITex"
static const ALIGN_ASSET(2) char gPauseSave10CHITex[] = dgPauseSave10CHITex;
#define dgPauseSaveConfirmationCHITex "__OTR__textures/icon_item_nes_static/gPauseSaveConfirmationCHITex"
static const ALIGN_ASSET(2) char gPauseSaveConfirmationCHITex[] = dgPauseSaveConfirmationCHITex;
#define dgPauseSavePromptCHITex "__OTR__textures/icon_item_nes_static/gPauseSavePromptCHITex"
static const ALIGN_ASSET(2) char gPauseSavePromptCHITex[] = dgPauseSavePromptCHITex;
#define dgPauseSelectItem00CHITex "__OTR__textures/icon_item_nes_static/gPauseSelectItem00CHITex"
static const ALIGN_ASSET(2) char gPauseSelectItem00CHITex[] = dgPauseSelectItem00CHITex;
#define dgPauseSelectItem10CHITex "__OTR__textures/icon_item_nes_static/gPauseSelectItem10CHITex"
static const ALIGN_ASSET(2) char gPauseSelectItem10CHITex[] = dgPauseSelectItem10CHITex;
#define dgPauseSelectItem20CHITex "__OTR__textures/icon_item_nes_static/gPauseSelectItem20CHITex"
static const ALIGN_ASSET(2) char gPauseSelectItem20CHITex[] = dgPauseSelectItem20CHITex;
#define dgPauseShadowTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseShadowTitleCHITex"
static const ALIGN_ASSET(2) char gPauseShadowTitleCHITex[] = dgPauseShadowTitleCHITex;
#define dgPauseSpiritTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseSpiritTitleCHITex"
static const ALIGN_ASSET(2) char gPauseSpiritTitleCHITex[] = dgPauseSpiritTitleCHITex;
#define dgPauseToDecideCHITex "__OTR__textures/icon_item_nes_static/gPauseToDecideCHITex"
static const ALIGN_ASSET(2) char gPauseToDecideCHITex[] = dgPauseToDecideCHITex;
#define dgPauseToEquipCHITex "__OTR__textures/icon_item_nes_static/gPauseToEquipCHITex"
static const ALIGN_ASSET(2) char gPauseToEquipCHITex[] = dgPauseToEquipCHITex;
#define dgPauseToEquipmentCHITex "__OTR__textures/icon_item_nes_static/gPauseToEquipmentCHITex"
static const ALIGN_ASSET(2) char gPauseToEquipmentCHITex[] = dgPauseToEquipmentCHITex;
#define dgPauseToMapCHITex "__OTR__textures/icon_item_nes_static/gPauseToMapCHITex"
static const ALIGN_ASSET(2) char gPauseToMapCHITex[] = dgPauseToMapCHITex;
#define dgPauseToPlayMelodyCHITex "__OTR__textures/icon_item_nes_static/gPauseToPlayMelodyCHITex"
static const ALIGN_ASSET(2) char gPauseToPlayMelodyCHITex[] = dgPauseToPlayMelodyCHITex;
#define dgPauseToQuestStatusCHITex "__OTR__textures/icon_item_nes_static/gPauseToQuestStatusCHITex"
static const ALIGN_ASSET(2) char gPauseToQuestStatusCHITex[] = dgPauseToQuestStatusCHITex;
#define dgPauseToSelectItemCHITex "__OTR__textures/icon_item_nes_static/gPauseToSelectItemCHITex"
static const ALIGN_ASSET(2) char gPauseToSelectItemCHITex[] = dgPauseToSelectItemCHITex;
#define dgPauseWaterTitleCHITex "__OTR__textures/icon_item_nes_static/gPauseWaterTitleCHITex"
static const ALIGN_ASSET(2) char gPauseWaterTitleCHITex[] = dgPauseWaterTitleCHITex;
#define dgPauseYesCHITex "__OTR__textures/icon_item_nes_static/gPauseYesCHITex"
static const ALIGN_ASSET(2) char gPauseYesCHITex[] = dgPauseYesCHITex;

// --- icon_item_static ---
#define dgItemIconSoldOutCHITex "__OTR__textures/icon_item_static/gItemIconSoldOutCHITex"
static const ALIGN_ASSET(2) char gItemIconSoldOutCHITex[] = dgItemIconSoldOutCHITex;

// --- item_name_static ---
#define dgBiggoronsSwordItemNameCHITex "__OTR__textures/item_name_static/gBiggoronsSwordItemNameCHITex"
static const ALIGN_ASSET(2) char gBiggoronsSwordItemNameCHITex[] = dgBiggoronsSwordItemNameCHITex;
#define dgBigPoeItemNameCHITex "__OTR__textures/item_name_static/gBigPoeItemNameCHITex"
static const ALIGN_ASSET(2) char gBigPoeItemNameCHITex[] = dgBigPoeItemNameCHITex;
#define dgBlueFireItemNameCHITex "__OTR__textures/item_name_static/gBlueFireItemNameCHITex"
static const ALIGN_ASSET(2) char gBlueFireItemNameCHITex[] = dgBlueFireItemNameCHITex;
#define dgBluePotionItemNameCHITex "__OTR__textures/item_name_static/gBluePotionItemNameCHITex"
static const ALIGN_ASSET(2) char gBluePotionItemNameCHITex[] = dgBluePotionItemNameCHITex;
#define dgBoleroOfFireItemNameCHITex "__OTR__textures/item_name_static/gBoleroOfFireItemNameCHITex"
static const ALIGN_ASSET(2) char gBoleroOfFireItemNameCHITex[] = dgBoleroOfFireItemNameCHITex;
#define dgBombBag20ItemNameCHITex "__OTR__textures/item_name_static/gBombBag20ItemNameCHITex"
static const ALIGN_ASSET(2) char gBombBag20ItemNameCHITex[] = dgBombBag20ItemNameCHITex;
#define dgBombBag30ItemNameCHITex "__OTR__textures/item_name_static/gBombBag30ItemNameCHITex"
static const ALIGN_ASSET(2) char gBombBag30ItemNameCHITex[] = dgBombBag30ItemNameCHITex;
#define dgBombBag40ItemNameCHITex "__OTR__textures/item_name_static/gBombBag40ItemNameCHITex"
static const ALIGN_ASSET(2) char gBombBag40ItemNameCHITex[] = dgBombBag40ItemNameCHITex;
#define dgBombchuItemNameCHITex "__OTR__textures/item_name_static/gBombchuItemNameCHITex"
static const ALIGN_ASSET(2) char gBombchuItemNameCHITex[] = dgBombchuItemNameCHITex;
#define dgBombItemNameCHITex "__OTR__textures/item_name_static/gBombItemNameCHITex"
static const ALIGN_ASSET(2) char gBombItemNameCHITex[] = dgBombItemNameCHITex;
#define dgBoomerangItemNameCHITex "__OTR__textures/item_name_static/gBoomerangItemNameCHITex"
static const ALIGN_ASSET(2) char gBoomerangItemNameCHITex[] = dgBoomerangItemNameCHITex;
#define dgBottledFairyItemNameCHITex "__OTR__textures/item_name_static/gBottledFairyItemNameCHITex"
static const ALIGN_ASSET(2) char gBottledFairyItemNameCHITex[] = dgBottledFairyItemNameCHITex;
#define dgBrokenGiantsKnifeItemNameCHITex "__OTR__textures/item_name_static/gBrokenGiantsKnifeItemNameCHITex"
static const ALIGN_ASSET(2) char gBrokenGiantsKnifeItemNameCHITex[] = dgBrokenGiantsKnifeItemNameCHITex;
#define dgBrokenGoronsSwordItemNameCHITex "__OTR__textures/item_name_static/gBrokenGoronsSwordItemNameCHITex"
static const ALIGN_ASSET(2) char gBrokenGoronsSwordItemNameCHITex[] = dgBrokenGoronsSwordItemNameCHITex;
#define dgBugItemNameCHITex "__OTR__textures/item_name_static/gBugItemNameCHITex"
static const ALIGN_ASSET(2) char gBugItemNameCHITex[] = dgBugItemNameCHITex;
#define dgBulletBag30ItemNameCHITex "__OTR__textures/item_name_static/gBulletBag30ItemNameCHITex"
static const ALIGN_ASSET(2) char gBulletBag30ItemNameCHITex[] = dgBulletBag30ItemNameCHITex;
#define dgBulletBag40ItemNameCHITex "__OTR__textures/item_name_static/gBulletBag40ItemNameCHITex"
static const ALIGN_ASSET(2) char gBulletBag40ItemNameCHITex[] = dgBulletBag40ItemNameCHITex;
#define dgBulletBag50ItemNameCHITex "__OTR__textures/item_name_static/gBulletBag50ItemNameCHITex"
static const ALIGN_ASSET(2) char gBulletBag50ItemNameCHITex[] = dgBulletBag50ItemNameCHITex;
#define dgBunnyHoodItemNameCHITex "__OTR__textures/item_name_static/gBunnyHoodItemNameCHITex"
static const ALIGN_ASSET(2) char gBunnyHoodItemNameCHITex[] = dgBunnyHoodItemNameCHITex;
#define dgClaimCheckItemNameCHITex "__OTR__textures/item_name_static/gClaimCheckItemNameCHITex"
static const ALIGN_ASSET(2) char gClaimCheckItemNameCHITex[] = dgClaimCheckItemNameCHITex;
#define dgCojiroItemNameCHITex "__OTR__textures/item_name_static/gCojiroItemNameCHITex"
static const ALIGN_ASSET(2) char gCojiroItemNameCHITex[] = dgCojiroItemNameCHITex;
#define dgCompassItemNameCHITex "__OTR__textures/item_name_static/gCompassItemNameCHITex"
static const ALIGN_ASSET(2) char gCompassItemNameCHITex[] = dgCompassItemNameCHITex;
#define dgCuccoItemNameCHITex "__OTR__textures/item_name_static/gCuccoItemNameCHITex"
static const ALIGN_ASSET(2) char gCuccoItemNameCHITex[] = dgCuccoItemNameCHITex;
#define dgDekuNutItemNameCHITex "__OTR__textures/item_name_static/gDekuNutItemNameCHITex"
static const ALIGN_ASSET(2) char gDekuNutItemNameCHITex[] = dgDekuNutItemNameCHITex;
#define dgDekuShieldItemNameCHITex "__OTR__textures/item_name_static/gDekuShieldItemNameCHITex"
static const ALIGN_ASSET(2) char gDekuShieldItemNameCHITex[] = dgDekuShieldItemNameCHITex;
#define dgDekuStickItemNameCHITex "__OTR__textures/item_name_static/gDekuStickItemNameCHITex"
static const ALIGN_ASSET(2) char gDekuStickItemNameCHITex[] = dgDekuStickItemNameCHITex;
#define dgDinsFireItemNameCHITex "__OTR__textures/item_name_static/gDinsFireItemNameCHITex"
static const ALIGN_ASSET(2) char gDinsFireItemNameCHITex[] = dgDinsFireItemNameCHITex;
#define dgDungeonMapItemNameCHITex "__OTR__textures/item_name_static/gDungeonMapItemNameCHITex"
static const ALIGN_ASSET(2) char gDungeonMapItemNameCHITex[] = dgDungeonMapItemNameCHITex;
#define dgEmptyBottleItemNameCHITex "__OTR__textures/item_name_static/gEmptyBottleItemNameCHITex"
static const ALIGN_ASSET(2) char gEmptyBottleItemNameCHITex[] = dgEmptyBottleItemNameCHITex;
#define dgEponasSongItemNameCHITex "__OTR__textures/item_name_static/gEponasSongItemNameCHITex"
static const ALIGN_ASSET(2) char gEponasSongItemNameCHITex[] = dgEponasSongItemNameCHITex;
#define dgEyeBallFrogItemNameCHITex "__OTR__textures/item_name_static/gEyeBallFrogItemNameCHITex"
static const ALIGN_ASSET(2) char gEyeBallFrogItemNameCHITex[] = dgEyeBallFrogItemNameCHITex;
#define dgEyeDropsItemNameCHITex "__OTR__textures/item_name_static/gEyeDropsItemNameCHITex"
static const ALIGN_ASSET(2) char gEyeDropsItemNameCHITex[] = dgEyeDropsItemNameCHITex;
#define dgFairyBowItemNameCHITex "__OTR__textures/item_name_static/gFairyBowItemNameCHITex"
static const ALIGN_ASSET(2) char gFairyBowItemNameCHITex[] = dgFairyBowItemNameCHITex;
#define dgFairyOcarinaItemNameCHITex "__OTR__textures/item_name_static/gFairyOcarinaItemNameCHITex"
static const ALIGN_ASSET(2) char gFairyOcarinaItemNameCHITex[] = dgFairyOcarinaItemNameCHITex;
#define dgFairySlingshotItemNameCHITex "__OTR__textures/item_name_static/gFairySlingshotItemNameCHITex"
static const ALIGN_ASSET(2) char gFairySlingshotItemNameCHITex[] = dgFairySlingshotItemNameCHITex;
#define dgFaroresWindItemNameCHITex "__OTR__textures/item_name_static/gFaroresWindItemNameCHITex"
static const ALIGN_ASSET(2) char gFaroresWindItemNameCHITex[] = dgFaroresWindItemNameCHITex;
#define dgFireArrowItemNameCHITex "__OTR__textures/item_name_static/gFireArrowItemNameCHITex"
static const ALIGN_ASSET(2) char gFireArrowItemNameCHITex[] = dgFireArrowItemNameCHITex;
#define dgFireMedallionItemNameCHITex "__OTR__textures/item_name_static/gFireMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gFireMedallionItemNameCHITex[] = dgFireMedallionItemNameCHITex;
#define dgFishItemNameCHITex "__OTR__textures/item_name_static/gFishItemNameCHITex"
static const ALIGN_ASSET(2) char gFishItemNameCHITex[] = dgFishItemNameCHITex;
#define dgForestMedallionItemNameCHITex "__OTR__textures/item_name_static/gForestMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gForestMedallionItemNameCHITex[] = dgForestMedallionItemNameCHITex;
#define dgFullMilkItemNameCHITex "__OTR__textures/item_name_static/gFullMilkItemNameCHITex"
static const ALIGN_ASSET(2) char gFullMilkItemNameCHITex[] = dgFullMilkItemNameCHITex;
#define dgGerudoMaskItemNameCHITex "__OTR__textures/item_name_static/gGerudoMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gGerudoMaskItemNameCHITex[] = dgGerudoMaskItemNameCHITex;
#define dgGerudosCardItemNameCHITex "__OTR__textures/item_name_static/gGerudosCardItemNameCHITex"
static const ALIGN_ASSET(2) char gGerudosCardItemNameCHITex[] = dgGerudosCardItemNameCHITex;
#define dgGiantsKnifeItemNameCHITex "__OTR__textures/item_name_static/gGiantsKnifeItemNameCHITex"
static const ALIGN_ASSET(2) char gGiantsKnifeItemNameCHITex[] = dgGiantsKnifeItemNameCHITex;
#define dgGoldenGauntletsItemNameCHITex "__OTR__textures/item_name_static/gGoldenGauntletsItemNameCHITex"
static const ALIGN_ASSET(2) char gGoldenGauntletsItemNameCHITex[] = dgGoldenGauntletsItemNameCHITex;
#define dgGoldenScaleItemNameCHITex "__OTR__textures/item_name_static/gGoldenScaleItemNameCHITex"
static const ALIGN_ASSET(2) char gGoldenScaleItemNameCHITex[] = dgGoldenScaleItemNameCHITex;
#define dgGoldSkulltulaItemNameCHITex "__OTR__textures/item_name_static/gGoldSkulltulaItemNameCHITex"
static const ALIGN_ASSET(2) char gGoldSkulltulaItemNameCHITex[] = dgGoldSkulltulaItemNameCHITex;
#define dgGoronMaskItemNameCHITex "__OTR__textures/item_name_static/gGoronMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gGoronMaskItemNameCHITex[] = dgGoronMaskItemNameCHITex;
#define dgGoronsBraceletItemNameCHITex "__OTR__textures/item_name_static/gGoronsBraceletItemNameCHITex"
static const ALIGN_ASSET(2) char gGoronsBraceletItemNameCHITex[] = dgGoronsBraceletItemNameCHITex;
#define dgGoronsRubyItemNameCHITex "__OTR__textures/item_name_static/gGoronsRubyItemNameCHITex"
static const ALIGN_ASSET(2) char gGoronsRubyItemNameCHITex[] = dgGoronsRubyItemNameCHITex;
#define dgGoronTunicItemNameCHITex "__OTR__textures/item_name_static/gGoronTunicItemNameCHITex"
static const ALIGN_ASSET(2) char gGoronTunicItemNameCHITex[] = dgGoronTunicItemNameCHITex;
#define dgGreenPotionItemNameCHITex "__OTR__textures/item_name_static/gGreenPotionItemNameCHITex"
static const ALIGN_ASSET(2) char gGreenPotionItemNameCHITex[] = dgGreenPotionItemNameCHITex;
#define dgHalfMilkItemNameCHITex "__OTR__textures/item_name_static/gHalfMilkItemNameCHITex"
static const ALIGN_ASSET(2) char gHalfMilkItemNameCHITex[] = dgHalfMilkItemNameCHITex;
#define dgHookshotItemNameCHITex "__OTR__textures/item_name_static/gHookshotItemNameCHITex"
static const ALIGN_ASSET(2) char gHookshotItemNameCHITex[] = dgHookshotItemNameCHITex;
#define dgHoverBootsItemNameCHITex "__OTR__textures/item_name_static/gHoverBootsItemNameCHITex"
static const ALIGN_ASSET(2) char gHoverBootsItemNameCHITex[] = dgHoverBootsItemNameCHITex;
#define dgHylianShieldItemNameCHITex "__OTR__textures/item_name_static/gHylianShieldItemNameCHITex"
static const ALIGN_ASSET(2) char gHylianShieldItemNameCHITex[] = dgHylianShieldItemNameCHITex;
#define dgIceArrowItemNameCHITex "__OTR__textures/item_name_static/gIceArrowItemNameCHITex"
static const ALIGN_ASSET(2) char gIceArrowItemNameCHITex[] = dgIceArrowItemNameCHITex;
#define dgIronBootsItemNameCHITex "__OTR__textures/item_name_static/gIronBootsItemNameCHITex"
static const ALIGN_ASSET(2) char gIronBootsItemNameCHITex[] = dgIronBootsItemNameCHITex;
#define dgKeatonMaskItemNameCHITex "__OTR__textures/item_name_static/gKeatonMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gKeatonMaskItemNameCHITex[] = dgKeatonMaskItemNameCHITex;
#define dgKokiriBootsItemNameCHITex "__OTR__textures/item_name_static/gKokiriBootsItemNameCHITex"
static const ALIGN_ASSET(2) char gKokiriBootsItemNameCHITex[] = dgKokiriBootsItemNameCHITex;
#define dgKokiriEmeraldItemNameCHITex "__OTR__textures/item_name_static/gKokiriEmeraldItemNameCHITex"
static const ALIGN_ASSET(2) char gKokiriEmeraldItemNameCHITex[] = dgKokiriEmeraldItemNameCHITex;
#define dgKokiriSwordItemNameCHITex "__OTR__textures/item_name_static/gKokiriSwordItemNameCHITex"
static const ALIGN_ASSET(2) char gKokiriSwordItemNameCHITex[] = dgKokiriSwordItemNameCHITex;
#define dgKokiriTunicItemNameCHITex "__OTR__textures/item_name_static/gKokiriTunicItemNameCHITex"
static const ALIGN_ASSET(2) char gKokiriTunicItemNameCHITex[] = dgKokiriTunicItemNameCHITex;
#define dgLensItemNameCHITex "__OTR__textures/item_name_static/gLensItemNameCHITex"
static const ALIGN_ASSET(2) char gLensItemNameCHITex[] = dgLensItemNameCHITex;
#define dgLightArrowItemNameCHITex "__OTR__textures/item_name_static/gLightArrowItemNameCHITex"
static const ALIGN_ASSET(2) char gLightArrowItemNameCHITex[] = dgLightArrowItemNameCHITex;
#define dgLightMedallionItemNameCHITex "__OTR__textures/item_name_static/gLightMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gLightMedallionItemNameCHITex[] = dgLightMedallionItemNameCHITex;
#define dgLongshotItemNameCHITex "__OTR__textures/item_name_static/gLongshotItemNameCHITex"
static const ALIGN_ASSET(2) char gLongshotItemNameCHITex[] = dgLongshotItemNameCHITex;
#define dgMagicBeansItemNameCHITex "__OTR__textures/item_name_static/gMagicBeansItemNameCHITex"
static const ALIGN_ASSET(2) char gMagicBeansItemNameCHITex[] = dgMagicBeansItemNameCHITex;
#define dgMaskofTruthItemNameCHITex "__OTR__textures/item_name_static/gMaskofTruthItemNameCHITex"
static const ALIGN_ASSET(2) char gMaskofTruthItemNameCHITex[] = dgMaskofTruthItemNameCHITex;
#define dgMasterSwordItemNameCHITex "__OTR__textures/item_name_static/gMasterSwordItemNameCHITex"
static const ALIGN_ASSET(2) char gMasterSwordItemNameCHITex[] = dgMasterSwordItemNameCHITex;
#define dgMegatonHammerItemNameCHITex "__OTR__textures/item_name_static/gMegatonHammerItemNameCHITex"
static const ALIGN_ASSET(2) char gMegatonHammerItemNameCHITex[] = dgMegatonHammerItemNameCHITex;
#define dgMinuetOfForestItemNameCHITex "__OTR__textures/item_name_static/gMinuetOfForestItemNameCHITex"
static const ALIGN_ASSET(2) char gMinuetOfForestItemNameCHITex[] = dgMinuetOfForestItemNameCHITex;
#define dgMirrorShieldItemNameCHITex "__OTR__textures/item_name_static/gMirrorShieldItemNameCHITex"
static const ALIGN_ASSET(2) char gMirrorShieldItemNameCHITex[] = dgMirrorShieldItemNameCHITex;
#define dgNayrusLoveItemNameCHITex "__OTR__textures/item_name_static/gNayrusLoveItemNameCHITex"
static const ALIGN_ASSET(2) char gNayrusLoveItemNameCHITex[] = dgNayrusLoveItemNameCHITex;
#define dgNocturneOfShadowItemNameCHITex "__OTR__textures/item_name_static/gNocturneOfShadowItemNameCHITex"
static const ALIGN_ASSET(2) char gNocturneOfShadowItemNameCHITex[] = dgNocturneOfShadowItemNameCHITex;
#define dgOcarinaOfTimeItemNameCHITex "__OTR__textures/item_name_static/gOcarinaOfTimeItemNameCHITex"
static const ALIGN_ASSET(2) char gOcarinaOfTimeItemNameCHITex[] = dgOcarinaOfTimeItemNameCHITex;
#define dgOddMushroomItemNameCHITex "__OTR__textures/item_name_static/gOddMushroomItemNameCHITex"
static const ALIGN_ASSET(2) char gOddMushroomItemNameCHITex[] = dgOddMushroomItemNameCHITex;
#define dgOddPotionItemNameCHITex "__OTR__textures/item_name_static/gOddPotionItemNameCHITex"
static const ALIGN_ASSET(2) char gOddPotionItemNameCHITex[] = dgOddPotionItemNameCHITex;
#define dgPieceOfHeartItemNameCHITex "__OTR__textures/item_name_static/gPieceOfHeartItemNameCHITex"
static const ALIGN_ASSET(2) char gPieceOfHeartItemNameCHITex[] = dgPieceOfHeartItemNameCHITex;
#define dgPoachersSawItemNameCHITex "__OTR__textures/item_name_static/gPoachersSawItemNameCHITex"
static const ALIGN_ASSET(2) char gPoachersSawItemNameCHITex[] = dgPoachersSawItemNameCHITex;
#define dgPocketCuccoItemNameCHITex "__OTR__textures/item_name_static/gPocketCuccoItemNameCHITex"
static const ALIGN_ASSET(2) char gPocketCuccoItemNameCHITex[] = dgPocketCuccoItemNameCHITex;
#define dgPocketEggItemNameCHITex "__OTR__textures/item_name_static/gPocketEggItemNameCHITex"
static const ALIGN_ASSET(2) char gPocketEggItemNameCHITex[] = dgPocketEggItemNameCHITex;
#define dgPoeItemNameCHITex "__OTR__textures/item_name_static/gPoeItemNameCHITex"
static const ALIGN_ASSET(2) char gPoeItemNameCHITex[] = dgPoeItemNameCHITex;
#define dgPreludeOfLightItemNameCHITex "__OTR__textures/item_name_static/gPreludeOfLightItemNameCHITex"
static const ALIGN_ASSET(2) char gPreludeOfLightItemNameCHITex[] = dgPreludeOfLightItemNameCHITex;
#define dgPrescriptionItemNameCHITex "__OTR__textures/item_name_static/gPrescriptionItemNameCHITex"
static const ALIGN_ASSET(2) char gPrescriptionItemNameCHITex[] = dgPrescriptionItemNameCHITex;
#define dgQuiver30ItemNameCHITex "__OTR__textures/item_name_static/gQuiver30ItemNameCHITex"
static const ALIGN_ASSET(2) char gQuiver30ItemNameCHITex[] = dgQuiver30ItemNameCHITex;
#define dgQuiver40ItemNameCHITex "__OTR__textures/item_name_static/gQuiver40ItemNameCHITex"
static const ALIGN_ASSET(2) char gQuiver40ItemNameCHITex[] = dgQuiver40ItemNameCHITex;
#define dgQuiver50ItemNameCHITex "__OTR__textures/item_name_static/gQuiver50ItemNameCHITex"
static const ALIGN_ASSET(2) char gQuiver50ItemNameCHITex[] = dgQuiver50ItemNameCHITex;
#define dgRedPotionItemNameCHITex "__OTR__textures/item_name_static/gRedPotionItemNameCHITex"
static const ALIGN_ASSET(2) char gRedPotionItemNameCHITex[] = dgRedPotionItemNameCHITex;
#define dgRequiemOfSpiritItemNameCHITex "__OTR__textures/item_name_static/gRequiemOfSpiritItemNameCHITex"
static const ALIGN_ASSET(2) char gRequiemOfSpiritItemNameCHITex[] = dgRequiemOfSpiritItemNameCHITex;
#define dgRutosLetterItemNameCHITex "__OTR__textures/item_name_static/gRutosLetterItemNameCHITex"
static const ALIGN_ASSET(2) char gRutosLetterItemNameCHITex[] = dgRutosLetterItemNameCHITex;
#define dgSariasSongItemNameCHITex "__OTR__textures/item_name_static/gSariasSongItemNameCHITex"
static const ALIGN_ASSET(2) char gSariasSongItemNameCHITex[] = dgSariasSongItemNameCHITex;
#define dgSerenadeOfWaterItemNameCHITex "__OTR__textures/item_name_static/gSerenadeOfWaterItemNameCHITex"
static const ALIGN_ASSET(2) char gSerenadeOfWaterItemNameCHITex[] = dgSerenadeOfWaterItemNameCHITex;
#define dgShadowMedallionItemNameCHITex "__OTR__textures/item_name_static/gShadowMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gShadowMedallionItemNameCHITex[] = dgShadowMedallionItemNameCHITex;
#define dgSilverGauntletsItemNameCHITex "__OTR__textures/item_name_static/gSilverGauntletsItemNameCHITex"
static const ALIGN_ASSET(2) char gSilverGauntletsItemNameCHITex[] = dgSilverGauntletsItemNameCHITex;
#define dgSilverScaleItemNameCHITex "__OTR__textures/item_name_static/gSilverScaleItemNameCHITex"
static const ALIGN_ASSET(2) char gSilverScaleItemNameCHITex[] = dgSilverScaleItemNameCHITex;
#define dgSkullMaskItemNameCHITex "__OTR__textures/item_name_static/gSkullMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gSkullMaskItemNameCHITex[] = dgSkullMaskItemNameCHITex;
#define dgSOLDOUTItemNameCHITex "__OTR__textures/item_name_static/gSOLDOUTItemNameCHITex"
static const ALIGN_ASSET(2) char gSOLDOUTItemNameCHITex[] = dgSOLDOUTItemNameCHITex;
#define dgSongOfStormsItemNameCHITex "__OTR__textures/item_name_static/gSongOfStormsItemNameCHITex"
static const ALIGN_ASSET(2) char gSongOfStormsItemNameCHITex[] = dgSongOfStormsItemNameCHITex;
#define dgSongOfTimeItemNameCHITex "__OTR__textures/item_name_static/gSongOfTimeItemNameCHITex"
static const ALIGN_ASSET(2) char gSongOfTimeItemNameCHITex[] = dgSongOfTimeItemNameCHITex;
#define dgSpiritMedallionItemNameCHITex "__OTR__textures/item_name_static/gSpiritMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gSpiritMedallionItemNameCHITex[] = dgSpiritMedallionItemNameCHITex;
#define dgSpookyMaskItemNameCHITex "__OTR__textures/item_name_static/gSpookyMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gSpookyMaskItemNameCHITex[] = dgSpookyMaskItemNameCHITex;
#define dgStoneofAgonyItemNameCHITex "__OTR__textures/item_name_static/gStoneofAgonyItemNameCHITex"
static const ALIGN_ASSET(2) char gStoneofAgonyItemNameCHITex[] = dgStoneofAgonyItemNameCHITex;
#define dgSunsSongItemNameCHITex "__OTR__textures/item_name_static/gSunsSongItemNameCHITex"
static const ALIGN_ASSET(2) char gSunsSongItemNameCHITex[] = dgSunsSongItemNameCHITex;
#define dgUnusedBigKeyItemNameCHITex "__OTR__textures/item_name_static/gUnusedBigKeyItemNameCHITex"
static const ALIGN_ASSET(2) char gUnusedBigKeyItemNameCHITex[] = dgUnusedBigKeyItemNameCHITex;
#define dgWaterMedallionItemNameCHITex "__OTR__textures/item_name_static/gWaterMedallionItemNameCHITex"
static const ALIGN_ASSET(2) char gWaterMedallionItemNameCHITex[] = dgWaterMedallionItemNameCHITex;
#define dgWeirdEggItemNameCHITex "__OTR__textures/item_name_static/gWeirdEggItemNameCHITex"
static const ALIGN_ASSET(2) char gWeirdEggItemNameCHITex[] = dgWeirdEggItemNameCHITex;
#define dgZeldasLetterItemNameCHITex "__OTR__textures/item_name_static/gZeldasLetterItemNameCHITex"
static const ALIGN_ASSET(2) char gZeldasLetterItemNameCHITex[] = dgZeldasLetterItemNameCHITex;
#define dgZeldasLullabyItemNameCHITex "__OTR__textures/item_name_static/gZeldasLullabyItemNameCHITex"
static const ALIGN_ASSET(2) char gZeldasLullabyItemNameCHITex[] = dgZeldasLullabyItemNameCHITex;
#define dgZoraMaskItemNameCHITex "__OTR__textures/item_name_static/gZoraMaskItemNameCHITex"
static const ALIGN_ASSET(2) char gZoraMaskItemNameCHITex[] = dgZoraMaskItemNameCHITex;
#define dgZorasSapphireItemNameCHITex "__OTR__textures/item_name_static/gZorasSapphireItemNameCHITex"
static const ALIGN_ASSET(2) char gZorasSapphireItemNameCHITex[] = dgZorasSapphireItemNameCHITex;
#define dgZoraTunicItemNameCHITex "__OTR__textures/item_name_static/gZoraTunicItemNameCHITex"
static const ALIGN_ASSET(2) char gZoraTunicItemNameCHITex[] = dgZoraTunicItemNameCHITex;

// --- map_name_static ---
#define dgDeathMountainCraterPositionNameCHITex "__OTR__textures/map_name_static/gDeathMountainCraterPositionNameCHITex"
static const ALIGN_ASSET(2) char gDeathMountainCraterPositionNameCHITex[] = dgDeathMountainCraterPositionNameCHITex;
#define dgDeathMountainPointNameCHITex "__OTR__textures/map_name_static/gDeathMountainPointNameCHITex"
static const ALIGN_ASSET(2) char gDeathMountainPointNameCHITex[] = dgDeathMountainPointNameCHITex;
#define dgDeathMountainTrailPositionNameCHITex "__OTR__textures/map_name_static/gDeathMountainTrailPositionNameCHITex"
static const ALIGN_ASSET(2) char gDeathMountainTrailPositionNameCHITex[] = dgDeathMountainTrailPositionNameCHITex;
#define dgDesertColossusPositionNameCHITex "__OTR__textures/map_name_static/gDesertColossusPositionNameCHITex"
static const ALIGN_ASSET(2) char gDesertColossusPositionNameCHITex[] = dgDesertColossusPositionNameCHITex;
#define dgGanonsCastlePositionNameCHITex "__OTR__textures/map_name_static/gGanonsCastlePositionNameCHITex"
static const ALIGN_ASSET(2) char gGanonsCastlePositionNameCHITex[] = dgGanonsCastlePositionNameCHITex;
#define dgGerudosFortressPointNameCHITex "__OTR__textures/map_name_static/gGerudosFortressPointNameCHITex"
static const ALIGN_ASSET(2) char gGerudosFortressPointNameCHITex[] = dgGerudosFortressPointNameCHITex;
#define dgGerudosFortressPositionNameCHITex "__OTR__textures/map_name_static/gGerudosFortressPositionNameCHITex"
static const ALIGN_ASSET(2) char gGerudosFortressPositionNameCHITex[] = dgGerudosFortressPositionNameCHITex;
#define dgGerudoValleyPointNameCHITex "__OTR__textures/map_name_static/gGerudoValleyPointNameCHITex"
static const ALIGN_ASSET(2) char gGerudoValleyPointNameCHITex[] = dgGerudoValleyPointNameCHITex;
#define dgGerudoValleyPositionNameCHITex "__OTR__textures/map_name_static/gGerudoValleyPositionNameCHITex"
static const ALIGN_ASSET(2) char gGerudoValleyPositionNameCHITex[] = dgGerudoValleyPositionNameCHITex;
#define dgGoronCityPositionNameCHITex "__OTR__textures/map_name_static/gGoronCityPositionNameCHITex"
static const ALIGN_ASSET(2) char gGoronCityPositionNameCHITex[] = dgGoronCityPositionNameCHITex;
#define dgGraveyardPositionNameCHITex "__OTR__textures/map_name_static/gGraveyardPositionNameCHITex"
static const ALIGN_ASSET(2) char gGraveyardPositionNameCHITex[] = dgGraveyardPositionNameCHITex;
#define dgHauntedWastelandPointNameCHITex "__OTR__textures/map_name_static/gHauntedWastelandPointNameCHITex"
static const ALIGN_ASSET(2) char gHauntedWastelandPointNameCHITex[] = dgHauntedWastelandPointNameCHITex;
#define dgHauntedWastelandPositionNameCHITex "__OTR__textures/map_name_static/gHauntedWastelandPositionNameCHITex"
static const ALIGN_ASSET(2) char gHauntedWastelandPositionNameCHITex[] = dgHauntedWastelandPositionNameCHITex;
#define dgHyliaLakesidePointNameCHITex "__OTR__textures/map_name_static/gHyliaLakesidePointNameCHITex"
static const ALIGN_ASSET(2) char gHyliaLakesidePointNameCHITex[] = dgHyliaLakesidePointNameCHITex;
#define dgHyruleCastlePositionNameCHITex "__OTR__textures/map_name_static/gHyruleCastlePositionNameCHITex"
static const ALIGN_ASSET(2) char gHyruleCastlePositionNameCHITex[] = dgHyruleCastlePositionNameCHITex;
#define dgHyruleFieldPointNameCHITex "__OTR__textures/map_name_static/gHyruleFieldPointNameCHITex"
static const ALIGN_ASSET(2) char gHyruleFieldPointNameCHITex[] = dgHyruleFieldPointNameCHITex;
#define dgHyruleFieldPositionNameCHITex "__OTR__textures/map_name_static/gHyruleFieldPositionNameCHITex"
static const ALIGN_ASSET(2) char gHyruleFieldPositionNameCHITex[] = dgHyruleFieldPositionNameCHITex;
#define dgKakarikoVillagePointNameCHITex "__OTR__textures/map_name_static/gKakarikoVillagePointNameCHITex"
static const ALIGN_ASSET(2) char gKakarikoVillagePointNameCHITex[] = dgKakarikoVillagePointNameCHITex;
#define dgKakarikoVillagePositionNameCHITex "__OTR__textures/map_name_static/gKakarikoVillagePositionNameCHITex"
static const ALIGN_ASSET(2) char gKakarikoVillagePositionNameCHITex[] = dgKakarikoVillagePositionNameCHITex;
#define dgKokiriForestPointNameCHITex "__OTR__textures/map_name_static/gKokiriForestPointNameCHITex"
static const ALIGN_ASSET(2) char gKokiriForestPointNameCHITex[] = dgKokiriForestPointNameCHITex;
#define dgKokiriForestPositionNameCHITex "__OTR__textures/map_name_static/gKokiriForestPositionNameCHITex"
static const ALIGN_ASSET(2) char gKokiriForestPositionNameCHITex[] = dgKokiriForestPositionNameCHITex;
#define dgLakeHyliaPositionNameCHITex "__OTR__textures/map_name_static/gLakeHyliaPositionNameCHITex"
static const ALIGN_ASSET(2) char gLakeHyliaPositionNameCHITex[] = dgLakeHyliaPositionNameCHITex;
#define dgLonLonRanchPointNameCHITex "__OTR__textures/map_name_static/gLonLonRanchPointNameCHITex"
static const ALIGN_ASSET(2) char gLonLonRanchPointNameCHITex[] = dgLonLonRanchPointNameCHITex;
#define dgLonLonRanchPositionNameCHITex "__OTR__textures/map_name_static/gLonLonRanchPositionNameCHITex"
static const ALIGN_ASSET(2) char gLonLonRanchPositionNameCHITex[] = dgLonLonRanchPositionNameCHITex;
#define dgLostWoodsPointNameCHITex "__OTR__textures/map_name_static/gLostWoodsPointNameCHITex"
static const ALIGN_ASSET(2) char gLostWoodsPointNameCHITex[] = dgLostWoodsPointNameCHITex;
#define dgLostWoodsPositionNameCHITex "__OTR__textures/map_name_static/gLostWoodsPositionNameCHITex"
static const ALIGN_ASSET(2) char gLostWoodsPositionNameCHITex[] = dgLostWoodsPositionNameCHITex;
#define dgMarketPointNameCHITex "__OTR__textures/map_name_static/gMarketPointNameCHITex"
static const ALIGN_ASSET(2) char gMarketPointNameCHITex[] = dgMarketPointNameCHITex;
#define dgMarketPositionNameCHITex "__OTR__textures/map_name_static/gMarketPositionNameCHITex"
static const ALIGN_ASSET(2) char gMarketPositionNameCHITex[] = dgMarketPositionNameCHITex;
#define dgQuestionMarkPositionNameCHITex "__OTR__textures/map_name_static/gQuestionMarkPositionNameCHITex"
static const ALIGN_ASSET(2) char gQuestionMarkPositionNameCHITex[] = dgQuestionMarkPositionNameCHITex;
#define dgSacredForestMeadowPositionNameCHITex "__OTR__textures/map_name_static/gSacredForestMeadowPositionNameCHITex"
static const ALIGN_ASSET(2) char gSacredForestMeadowPositionNameCHITex[] = dgSacredForestMeadowPositionNameCHITex;
#define dgZorasDomainPointNameCHITex "__OTR__textures/map_name_static/gZorasDomainPointNameCHITex"
static const ALIGN_ASSET(2) char gZorasDomainPointNameCHITex[] = dgZorasDomainPointNameCHITex;
#define dgZorasDomainPositionNameCHITex "__OTR__textures/map_name_static/gZorasDomainPositionNameCHITex"
static const ALIGN_ASSET(2) char gZorasDomainPositionNameCHITex[] = dgZorasDomainPositionNameCHITex;
#define dgZorasFountainPositionNameCHITex "__OTR__textures/map_name_static/gZorasFountainPositionNameCHITex"
static const ALIGN_ASSET(2) char gZorasFountainPositionNameCHITex[] = dgZorasFountainPositionNameCHITex;
#define dgZorasRiverPositionNameCHITex "__OTR__textures/map_name_static/gZorasRiverPositionNameCHITex"
static const ALIGN_ASSET(2) char gZorasRiverPositionNameCHITex[] = dgZorasRiverPositionNameCHITex;

// --- object_bv ---
#define dgBarinadeTitleCardCHITex "__OTR__textures/object_bv/gBarinadeTitleCardCHITex"
static const ALIGN_ASSET(2) char gBarinadeTitleCardCHITex[] = dgBarinadeTitleCardCHITex;

// --- object_fd ---
#define dgVolvagiaBossTitleCardCHITex "__OTR__textures/object_fd/gVolvagiaBossTitleCardCHITex"
static const ALIGN_ASSET(2) char gVolvagiaBossTitleCardCHITex[] = dgVolvagiaBossTitleCardCHITex;

// --- object_fhg ---
#define dgPhantomGanonTitleCardCHITex "__OTR__textures/object_fhg/gPhantomGanonTitleCardCHITex"
static const ALIGN_ASSET(2) char gPhantomGanonTitleCardCHITex[] = dgPhantomGanonTitleCardCHITex;

// --- object_ganon ---
#define dgGanondorfTitleCardCHITex "__OTR__textures/object_ganon/gGanondorfTitleCardCHITex"
static const ALIGN_ASSET(2) char gGanondorfTitleCardCHITex[] = dgGanondorfTitleCardCHITex;

// --- object_ganon2 ---
#define dgGanonTitleCardCHITex "__OTR__textures/object_ganon2/gGanonTitleCardCHITex"
static const ALIGN_ASSET(2) char gGanonTitleCardCHITex[] = dgGanonTitleCardCHITex;

// --- object_goma ---
#define dgGohmaTitleCardCHITex "__OTR__textures/object_goma/gGohmaTitleCardCHITex"
static const ALIGN_ASSET(2) char gGohmaTitleCardCHITex[] = dgGohmaTitleCardCHITex;

// --- object_kingdodongo ---
#define dgKingDodongoTitleCardCHITex "__OTR__textures/object_kingdodongo/gKingDodongoTitleCardCHITex"
static const ALIGN_ASSET(2) char gKingDodongoTitleCardCHITex[] = dgKingDodongoTitleCardCHITex;

// --- object_mo ---
#define dgMorphaTitleCardCHITex "__OTR__textures/object_mo/gMorphaTitleCardCHITex"
static const ALIGN_ASSET(2) char gMorphaTitleCardCHITex[] = dgMorphaTitleCardCHITex;

// --- object_sst ---
#define dgBongoTitleCardCHITex "__OTR__textures/object_sst/gBongoTitleCardCHITex"
static const ALIGN_ASSET(2) char gBongoTitleCardCHITex[] = dgBongoTitleCardCHITex;

// --- object_tw ---
#define dgTwinrovaTitleCardCHITex "__OTR__textures/object_tw/gTwinrovaTitleCardCHITex"
static const ALIGN_ASSET(2) char gTwinrovaTitleCardCHITex[] = dgTwinrovaTitleCardCHITex;

// --- parameter_static ---
#define dgNaviCUpCHITex "__OTR__textures/parameter_static/gNaviCUpCHITex"
static const ALIGN_ASSET(2) char gNaviCUpCHITex[] = dgNaviCUpCHITex;

// --- title_static ---
#define dgFileSelBossRushSettingsCHIText "__OTR__textures/title_static/gFileSelBossRushSettingsCHIText"
static const ALIGN_ASSET(2) char gFileSelBossRushSettingsCHIText[] = dgFileSelBossRushSettingsCHIText;
#define dgFileSelAreYouSure2CHITex "__OTR__textures/title_static/gFileSelAreYouSure2CHITex"
static const ALIGN_ASSET(2) char gFileSelAreYouSure2CHITex[] = dgFileSelAreYouSure2CHITex;
#define dgFileSelAreYouSureCHITex "__OTR__textures/title_static/gFileSelAreYouSureCHITex"
static const ALIGN_ASSET(2) char gFileSelAreYouSureCHITex[] = dgFileSelAreYouSureCHITex;
#define dgFileSelCheckBrightnessCHITex "__OTR__textures/title_static/gFileSelCheckBrightnessCHITex"
static const ALIGN_ASSET(2) char gFileSelCheckBrightnessCHITex[] = dgFileSelCheckBrightnessCHITex;
#define dgFileSelControlsCHITex "__OTR__textures/title_static/gFileSelControlsCHITex"
static const ALIGN_ASSET(2) char gFileSelControlsCHITex[] = dgFileSelControlsCHITex;
#define dgFileSelCopyButtonCHITex "__OTR__textures/title_static/gFileSelCopyButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelCopyButtonCHITex[] = dgFileSelCopyButtonCHITex;
#define dgFileSelCopyToWhichFileCHITex "__OTR__textures/title_static/gFileSelCopyToWhichFileCHITex"
static const ALIGN_ASSET(2) char gFileSelCopyToWhichFileCHITex[] = dgFileSelCopyToWhichFileCHITex;
#define dgFileSelCopyWhichFileCHITex "__OTR__textures/title_static/gFileSelCopyWhichFileCHITex"
static const ALIGN_ASSET(2) char gFileSelCopyWhichFileCHITex[] = dgFileSelCopyWhichFileCHITex;
#define dgFileSelENDButtonCHITex "__OTR__textures/title_static/gFileSelENDButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelENDButtonCHITex[] = dgFileSelENDButtonCHITex;
#define dgFileSelEraseButtonCHITex "__OTR__textures/title_static/gFileSelEraseButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelEraseButtonCHITex[] = dgFileSelEraseButtonCHITex;
#define dgFileSelEraseWhichFileCHITex "__OTR__textures/title_static/gFileSelEraseWhichFileCHITex"
static const ALIGN_ASSET(2) char gFileSelEraseWhichFileCHITex[] = dgFileSelEraseWhichFileCHITex;
#define dgFileSelFile1ButtonCHITex "__OTR__textures/title_static/gFileSelFile1ButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelFile1ButtonCHITex[] = dgFileSelFile1ButtonCHITex;
#define dgFileSelFile2ButtonCHITex "__OTR__textures/title_static/gFileSelFile2ButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelFile2ButtonCHITex[] = dgFileSelFile2ButtonCHITex;
#define dgFileSelFile3ButtonCHITex "__OTR__textures/title_static/gFileSelFile3ButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelFile3ButtonCHITex[] = dgFileSelFile3ButtonCHITex;
#define dgFileSelFileCopiedCHITex "__OTR__textures/title_static/gFileSelFileCopiedCHITex"
static const ALIGN_ASSET(2) char gFileSelFileCopiedCHITex[] = dgFileSelFileCopiedCHITex;
#define dgFileSelFileEmptyCHITex "__OTR__textures/title_static/gFileSelFileEmptyCHITex"
static const ALIGN_ASSET(2) char gFileSelFileEmptyCHITex[] = dgFileSelFileEmptyCHITex;
#define dgFileSelFileErasedCHITex "__OTR__textures/title_static/gFileSelFileErasedCHITex"
static const ALIGN_ASSET(2) char gFileSelFileErasedCHITex[] = dgFileSelFileErasedCHITex;
#define dgFileSelFileInUseCHITex "__OTR__textures/title_static/gFileSelFileInUseCHITex"
static const ALIGN_ASSET(2) char gFileSelFileInUseCHITex[] = dgFileSelFileInUseCHITex;
#define dgFileSelHeadsetCHITex "__OTR__textures/title_static/gFileSelHeadsetCHITex"
static const ALIGN_ASSET(2) char gFileSelHeadsetCHITex[] = dgFileSelHeadsetCHITex;
#define dgFileSelHoldCHITex "__OTR__textures/title_static/gFileSelHoldCHITex"
static const ALIGN_ASSET(2) char gFileSelHoldCHITex[] = dgFileSelHoldCHITex;
#define dgFileSelLTargetingCHITex "__OTR__textures/title_static/gFileSelLTargetingCHITex"
static const ALIGN_ASSET(2) char gFileSelLTargetingCHITex[] = dgFileSelLTargetingCHITex;
#define dgFileSelMonoCHITex "__OTR__textures/title_static/gFileSelMonoCHITex"
static const ALIGN_ASSET(2) char gFileSelMonoCHITex[] = dgFileSelMonoCHITex;
#define dgFileSelNameCHITex "__OTR__textures/title_static/gFileSelNameCHITex"
static const ALIGN_ASSET(2) char gFileSelNameCHITex[] = dgFileSelNameCHITex;
#define dgFileSelNoEmptyFileCHITex "__OTR__textures/title_static/gFileSelNoEmptyFileCHITex"
static const ALIGN_ASSET(2) char gFileSelNoEmptyFileCHITex[] = dgFileSelNoEmptyFileCHITex;
#define dgFileSelNoFileToCopyCHITex "__OTR__textures/title_static/gFileSelNoFileToCopyCHITex"
static const ALIGN_ASSET(2) char gFileSelNoFileToCopyCHITex[] = dgFileSelNoFileToCopyCHITex;
#define dgFileSelNoFileToEraseCHITex "__OTR__textures/title_static/gFileSelNoFileToEraseCHITex"
static const ALIGN_ASSET(2) char gFileSelNoFileToEraseCHITex[] = dgFileSelNoFileToEraseCHITex;
#define dgFileSelOpenThisFileCHITex "__OTR__textures/title_static/gFileSelOpenThisFileCHITex"
static const ALIGN_ASSET(2) char gFileSelOpenThisFileCHITex[] = dgFileSelOpenThisFileCHITex;
#define dgFileSelOptionsButtonCHITex "__OTR__textures/title_static/gFileSelOptionsButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelOptionsButtonCHITex[] = dgFileSelOptionsButtonCHITex;
#define dgFileSelOptionsCHITex "__OTR__textures/title_static/gFileSelOptionsCHITex"
static const ALIGN_ASSET(2) char gFileSelOptionsCHITex[] = dgFileSelOptionsCHITex;
#define dgFileSelPleaseSelectAFileCHITex "__OTR__textures/title_static/gFileSelPleaseSelectAFileCHITex"
static const ALIGN_ASSET(2) char gFileSelPleaseSelectAFileCHITex[] = dgFileSelPleaseSelectAFileCHITex;
#define dgFileSelPleaseChooseAQuestCHITex "__OTR__textures/title_static/gFileSelPleaseChooseAQuestCHITex"
static const ALIGN_ASSET(2) char gFileSelPleaseChooseAQuestCHITex[] = dgFileSelPleaseChooseAQuestCHITex;
#define dgFileSelQuitButtonCHITex "__OTR__textures/title_static/gFileSelQuitButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelQuitButtonCHITex[] = dgFileSelQuitButtonCHITex;
#define dgFileSelSOUNDCHITex "__OTR__textures/title_static/gFileSelSOUNDCHITex"
static const ALIGN_ASSET(2) char gFileSelSOUNDCHITex[] = dgFileSelSOUNDCHITex;
#define dgFileSelStereoCHITex "__OTR__textures/title_static/gFileSelStereoCHITex"
static const ALIGN_ASSET(2) char gFileSelStereoCHITex[] = dgFileSelStereoCHITex;
#define dgFileSelSurroundCHITex "__OTR__textures/title_static/gFileSelSurroundCHITex"
static const ALIGN_ASSET(2) char gFileSelSurroundCHITex[] = dgFileSelSurroundCHITex;
#define dgFileSelSwitchCHITex "__OTR__textures/title_static/gFileSelSwitchCHITex"
static const ALIGN_ASSET(2) char gFileSelSwitchCHITex[] = dgFileSelSwitchCHITex;
#define dgFileSelYesButtonCHITex "__OTR__textures/title_static/gFileSelYesButtonCHITex"
static const ALIGN_ASSET(2) char gFileSelYesButtonCHITex[] = dgFileSelYesButtonCHITex;

// #endregion

// #region SOH [Chinese] - object / overlay textures
// These live outside textures/*/ but follow the same OTR packing rules. They are
// declared here (rather than in the generated objects/*.h and overlays/*.h) for the
// same reason as above: asset regeneration must not be able to drop them.

#define dgTitleTitleCHITex "__OTR__objects/object_mag/gTitleTitleCHITex"
static const ALIGN_ASSET(2) char gTitleTitleCHITex[] = dgTitleTitleCHITex;

#define dsTheEndCHITex "__OTR__overlays/ovl_End_Title/sTheEndCHITex"
static const ALIGN_ASSET(2) char sTheEndCHITex[] = dsTheEndCHITex;

#define dsTheLegendOfZeldaCHITex "__OTR__overlays/ovl_End_Title/sTheLegendOfZeldaCHITex"
static const ALIGN_ASSET(2) char sTheLegendOfZeldaCHITex[] = dsTheLegendOfZeldaCHITex;

#define dsOcarinaOfTimeCHITex "__OTR__overlays/ovl_End_Title/sOcarinaOfTimeCHITex"
static const ALIGN_ASSET(2) char sOcarinaOfTimeCHITex[] = dsOcarinaOfTimeCHITex;
// #endregion

#endif
