"""Validate the UTF-8 UI catalog, generate its C++ table and subset its font."""
from pathlib import Path
import json
import re
import argparse

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser()
parser.add_argument('--font', type=Path)
parser.add_argument('--font-output', type=Path)
args = parser.parse_args()
entries = {}
formats = re.compile(r'(?<![0-9])%(?:[-+#0]*\d*(?:\.\d+)?(?:ll|[lhz])?[diuoxXfFeEgGcsp]|%)')
for path in sorted(Path(__file__).parent.glob('ui*.tsv')):
    for line in path.read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#'): continue
        key, value = line.split('\t', 1)
        key = key.replace('\\n', '\n').replace('\\t', '\t')
        value = value.replace('\\n', '\n').replace('\\t', '\t')
        if key in entries and entries[key] != value:
            raise ValueError(f'Duplicate translation: {key}')
        if formats.findall(key) != formats.findall(value):
            raise ValueError(f'Format mismatch: {key}')
        entries[key] = value
output = root / 'soh/soh/localization/ChineseUI.inc'
output.write_text('// Generated by scripts/chinese/build_ui.py.\n' + ''.join(
    '{' + json.dumps(k, ensure_ascii=False) + ', ' + json.dumps(v, ensure_ascii=False) + '},\n'
    for k, v in sorted(entries.items())), encoding='utf-8')
if args.font:
    from fontTools import subset
    from fontTools.ttLib import TTFont
    font = TTFont(args.font)
    glyphs = set(''.join(entries.values())) | set(chr(i) for i in range(32, 127))
    missing = sorted(ord(c) for c in glyphs if ord(c) >= 32 and ord(c) not in font.getBestCmap())
    if missing: raise ValueError(f'Missing font glyphs: {missing}')
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_legacy = True
    options.name_languages = ['*']
    sub = subset.Subsetter(options=options)
    sub.populate(text=''.join(glyphs))
    sub.subset(font)
    # The subset is a modified font: avoid the upstream reserved family names.
    for record in font['name'].names:
        if record.nameID in (1, 3, 4, 6, 16):
            record.string = 'Shipwright Chinese UI'.replace(' ', '' if record.nameID == 6 else ' ').encode(record.getEncoding())
    if 'CFF ' in font:
        font['CFF '].cff.fontNames = ['ShipwrightChineseUI']
        font['CFF '].cff.topDictIndex[0].FamilyName = 'Shipwright Chinese UI'
        font['CFF '].cff.topDictIndex[0].FullName = 'Shipwright Chinese UI'
    args.font_output.parent.mkdir(parents=True, exist_ok=True)
    font.save(args.font_output)
print(f'{len(entries)} validated UI translations')
